[deps]
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Sindbad = "6686e6de-2010-4bf8-9178-b2bcc470766e"
SindbadData = "772b809f-5329-4bfd-a2e9-cc4714ce84b1"
SindbadExperiment = "bbd31fc6-1b7a-43f2-b792-0273fef35116"
SindbadML = "eb1d8004-2d42-4eef-b369-ed0645c101e8"
SindbadMetrics = "7a8077d0-ecf5-44b0-95d4-89eadbafc35c"
SindbadOptimization = "64fff8bd-0c13-402c-aa96-b97d0bc3655c"
SindbadSetup = "2b7f2987-8a1e-48b4-8a02-cc9e7c4eeb1c"
SindbadTEM = "f6108451-10cb-42fa-b0c1-67671cf08f15"
SindbadUtils = "a2ad09c8-73f9-4387-ada0-5c5a8c58f8ab"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"

[sources]
Sindbad = {path = "../.."}
SindbadData = {path = "../../lib/SindbadData"}
SindbadExperiment = {path = "../../lib/SindbadExperiment"}
SindbadML = {path = "../../lib/SindbadML"}
SindbadMetrics = {path = "../../lib/SindbadMetrics"}
SindbadOptimization = {path = "../../lib/SindbadOptimization"}
SindbadSetup = {path = "../../lib/SindbadSetup"}
SindbadTEM = {path = "../../lib/SindbadTEM"}
SindbadUtils = {path = "../../lib/SindbadUtils"}